# Generated by Django 4.2.7 on 2023-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Start_year', models.DateField()),
                ('Course', models.IntegerField()),
                ('Group', models.IntegerField()),
                ('First_year', models.IntegerField()),
                ('Second_year', models.IntegerField()),
                ('Third_year', models.IntegerField()),
                ('Fourth_year', models.IntegerField()),
            ],
        ),
    ]
